[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "VarCas-OFFinder"
authors = [{name = "Abyot", email = "abyot@pusan.ac.kr"}]
dynamic = ["version", "description"]
